apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apachecassandra
  name: apachecassandra
spec:
  ports:
    - name: "9042"
      port: 9042
      targetPort: 9042
    - name: "9160"
      port: 9160
      targetPort: 9160
    - name: "7199"
      port: 7199
      targetPort: 7199
  selector:
    io.kompose.service: apachecassandra
status:
  loadBalancer: {}
