apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8080
  selector:
    io.kompose.service: consumer
status:
  loadBalancer: {}
