apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - image: eventconsumer:0.0.1
          name: consumer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
