apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: producer
  name: producer
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8080
  selector:
    io.kompose.service: producer
status:
  loadBalancer: {}
